### ISSUE TITLE
Patch 5.5 4k UI assets.

### ISSUE THREAD

**Issue by Avalon304** [skotlex/ffxiv-material-ui#207] opened 2021-04-13 10:03 UTC
Patch 5.5 added new high resolution assets for 4K, which doesnt work with MaterialUI.

**Comment by AxelPina** [comment] 2021-04-13 15:20
Pretty sure @skotlex has stopped working on this as per #203. Hopefully they can resume work on it whenever :(

**Comment by skotlex** [comment] 2021-04-13 15:26
I'm going to pay for the game for about a month to respond to the 5.5 patch. It's a duplicate of the #195 issue, but I'll try my best.

**Comment by PascalTemel** [comment] 2021-04-13 20:20
> I'm going to pay for the game for about a month to respond to the 5.5 patch. It's a duplicate of the #195 issue, but I'll try my best.

I'll paypal you the money if you'd like.

**Comment by skotlex** [comment] 2021-04-13 23:43
Oh, my God... Too many people sponsored it. I'll try to do it as fast as I can.
![02_모코코콘2_12_두렵다](https://user-images.githubusercontent.com/31692408/114634420-72b42680-9cfd-11eb-9588-0e7fb184df70.png)

**Comment by Theletha** [comment] 2021-04-16 18:15
awesome love your work!

**Closed** 2021-04-19 07:10 UTC
Labels: enhancement
