### ISSUE TITLE
Make it work on Endwalker

### ISSUE THREAD

**Issue by Power2All** [skotlex/ffxiv-material-ui#270] opened 2021-12-03 09:44 UTC
Right now, the UI doesn't work on Endwalker.
I rather got used to this interface, is there a patch coming that makes the UI work in Endwalker again ?

**Comment by skotlex** [comment] 2021-12-03 10:19
#271

**Comment by AmenneHolelane** [comment] 2021-12-03 12:00
duplicate of #271

**Closed by AmenneHolelane** 2021-12-03 12:00 UTC
Labels: enhancement
